#!/bin/bash

Url="http://dictionary.reference.com/browse/"

function usage() {
	echo "Usage: $(basename $0) <word>"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

Word=$1
wget -q -O - $Url$Word | grep -E -o '"http://.*.mp3"' | tr -d '"' | head -n1
