#!/bin/bash

Url="http://dictionary.reference.com/browse/"

function usage() {
	echo "Usage: $(basename $0) <word>"
}

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

Word=$1
wget -q -O - $Url$Word | \
grep -E -o '<span class="prondelim">/</span>.*<span class="prondelim">/</span>' | \
sed -r -e 's/span //g' -e 's/class="[a-z-]*"//g' -e 's/<\/span>//g' -e 's/<>//g' | \
sed -r -e 's/<a .*//g'
